/* Replace with your SQL commands */
CREATE TABLE public."users" (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(10485760) NOT NULL,
	"password" varchar(10485760) NOT NULL,
	first_name varchar(10485760) NULL,
	last_name varchar(10485760) NULL,
	phone varchar(10485760) NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	updated_at timestamp NOT NULL DEFAULT NOW(),
	resource_id varchar(10485760) NOT NULL,
	CONSTRAINT users_resource_id_uq UNIQUE (resource_id),
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_phone_un UNIQUE (phone),
	CONSTRAINT users_email_un UNIQUE (email)
);

CREATE TABLE public."roles" (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(10485760) NOT NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	updated_at timestamp NOT NULL DEFAULT NOW(),
	resource_id varchar(10485760) NOT NULL,
	CONSTRAINT users_resource_id_uq UNIQUE (resource_id),
	CONSTRAINT roles_pk PRIMARY KEY (id),
	CONSTRAINT roles_name_un UNIQUE (name)
);

CREATE TABLE public.user_has_roles (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id int NOT NULL,
	role_id int NOT NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	updated_at timestamp NOT NULL DEFAULT NOW(),
	resource_id varchar(10485760) NOT NULL,
	CONSTRAINT users_resource_id_uq UNIQUE (resource_id),
	CONSTRAINT user_has_roles_pk PRIMARY KEY (id),
	CONSTRAINT user_has_roles_un UNIQUE (user_id, role_id),
	CONSTRAINT user_has_roles_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT user_has_roles_role_id_fk FOREIGN KEY (role_id) REFERENCES public.roles(id)
);

CREATE TABLE public.permissions (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	updated_at timestamp NOT NULL DEFAULT NOW(),
	resource_id varchar(10485760) NOT NULL,
	CONSTRAINT users_resource_id_uq UNIQUE (resource_id),
	CONSTRAINT permissions_un UNIQUE (name),
	CONSTRAINT permissions_pk PRIMARY KEY (id)
);

CREATE TABLE public.role_has_permissions (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role_id int NOT NULL,
	permission_id int NOT NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	updated_at timestamp NOT NULL DEFAULT NOW(),
	resource_id varchar(10485760) NOT NULL,
	CONSTRAINT users_resource_id_uq UNIQUE (resource_id),
	CONSTRAINT role_has_pemissions_pk PRIMARY KEY (id),
	CONSTRAINT role_has_pemissions_un UNIQUE (role_id, permission_id),
	CONSTRAINT role_has_pemissions_role_id_fk FOREIGN KEY (role_id) REFERENCES public.roles(id),
	CONSTRAINT role_has_pemissions_permission_id_fk FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);

CREATE TABLE public.groups (
	id bigserial NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name int NOT NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	updated_at timestamp NOT NULL DEFAULT NOW(),
	resource_id varchar(10485760) NOT NULL,
	CONSTRAINT users_resource_id_uq UNIQUE (resource_id),
	CONSTRAINT role_has_pemissions_pk PRIMARY KEY (id),
	CONSTRAINT role_has_pemissions_un UNIQUE (name)
);