name: Build and Deploy

on: push

jobs:
    # JOB to run change detection
    changes:
        runs-on: ubuntu-latest
        # Set job outputs to values from filter step
        outputs:
            backend: ${{ steps.filter.outputs.backend }}
            frontend: ${{ steps.filter.outputs.frontend }}
        steps:
            # For pull requests it's not necessary to checkout the code
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      backend:
                        - 'backend/**'
                        - 'common/**'
                        - '.github/**'
                      frontend:
                        - 'frontend/**'
                        - 'common/**'
                        - '.github/**'

    frontend:
        needs: changes
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        name: Frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Dependencies Common
              working-directory: ./common
              run: npm install
            - name: Install Dependencies Frontend
              working-directory: ./frontend
              run: npm install --legacy-peer-deps
            - name: Build
              working-directory: ./frontend
              run: npm run build
            - name: Deploy to Firebase PRODUCTION
              if: github.ref == 'refs/heads/main'
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --project orma-playground
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
                  PROJECT_PATH: ./frontend
    backend:
        name: Backend
        needs: changes
        if: ${{ needs.changes.outputs.backend == 'true' && github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Install kubectl
              uses: azure/setup-kubectl@v4
              with:
                  version: latest

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: npm i -> backend
              run: cd backend && npm install

            - name: npm i -> common
              run: cd common && npm install

            - name: Build, push, and roll out
              run: cd backend && npm run deploy
              env:
                  KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
                  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
                  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
